package skustra.focusflow.ui.localization

sealed class LocalizationKey {
    object Remaining : LocalizationKey()
    object Start : LocalizationKey()
    object Pause : LocalizationKey()
    object Resume : LocalizationKey()
    object Stop : LocalizationKey()
    object MinutesShort : LocalizationKey()
    object Break : LocalizationKey()
    object CreateSession : LocalizationKey()
    object NoBreakIncluded : LocalizationKey()
    object SingleBreak : LocalizationKey()
    object BreakCount : LocalizationKey()
    object SkipBreaks : LocalizationKey()
    object SessionInProgress : LocalizationKey()
    object SessionInProgressDescription : LocalizationKey()
    object SessionPaused : LocalizationKey()
    object Mon : LocalizationKey()
    object Tue : LocalizationKey()
    object Wed : LocalizationKey()
    object Thu : LocalizationKey()
    object Fri : LocalizationKey()
    object Sat : LocalizationKey()
    object Sun : LocalizationKey()
    object DailyGoal : LocalizationKey()
    object YourProgress : LocalizationKey()
    object ChartDescription : LocalizationKey()
    object SessionIdleTitle : LocalizationKey()
    object SessionIdleDescription : LocalizationKey()
    object SessionPauseTitle : LocalizationKey()
    object SessionPauseDescription : LocalizationKey()
    object SessionInProgressTitle : LocalizationKey()
    object SessionBreakTitle : LocalizationKey()
    object SessionBreakDescription : LocalizationKey()
    object PostPermissionNeedMessage : LocalizationKey()
    object PostPermissionNeedMessageRationale : LocalizationKey()
    object Allow : LocalizationKey()

}